version: '3.3'

services:
        web:
          build:
            dockerfile: ./images/gitlab/Dockerfile.dropin
            context: .
          restart: always
          hostname: 'localhost'
          environment:
            GITLAB_OMNIBUS_CONFIG: |
              external_url 'https://localhost'
          ports:
            - '80:80'
            - '443:443'
            - '22:22'
